* ACT GC Paper Plots
Here I collect the scripts to make all kinds of plots in the act gc
paper.

** planck vs. act temperature map
- script: plot_planck_act_sidebyside.py
- data: planck, coadd
- run script:
  #+BEGIN_SRC bash
  python plot_planck_act_sidebyside.py -o plots --oname planck_coadd_sidebyside.pdf
  #+END_SRC
** QU in 3 bands
- script: plot_qu_in_3bands.py
- data: coadd
- run script:
  #+BEGIN_SRC bash
  python plot_qu_in_3bands.py -o plots
  #+END_SRC
** magnetic field in 3 bands
- script: plot_mag_in_3bands.py
- data: coadd
- run script
  #+BEGIN_SRC bash
  python plot_mag_in_3bands.py -o plots
  #+END_SRC
** polarization fraction
- plot polarization fraction per frequency
- script: plot_polfrac.py
- run script
  #+BEGIN_SRC bash
  python plot_polfrac.py -o plots --freq f090 --oname polfrac_f090.pdf --log
  python plot_polfrac.py -o plots --freq f150 --oname polfrac_f150.pdf --log
  python plot_polfrac.py -o plots --freq f220 --oname polfrac_f220.pdf --log
  #+END_SRC
  smooth version
  #+BEGIN_SRC bash
    python plot_polfrac.py -o plots --freq f090 --oname polfrac_f090_s2.pdf \
           --smooth 2 --cmap jet --min 0 --max 0.2
    python plot_polfrac.py -o plots --freq f150 --oname polfrac_f150_s2.pdf \
           --smooth 2 --cmap jet --min 0 --max 0.2
    python plot_polfrac.py -o plots --freq f220 --oname polfrac_f220_s2.pdf \
           --smooth 2 --cmap jet --min 0 --max 0.2
  #+END_SRC
** polarization uncertainties
- script plot_polangle_error.py
- run script
  #+BEGIN_SRC bash
  python plot_polangle_error.py -o plots --freq f090 --oname polang_err_f090.pdf
  python plot_polangle_error.py -o plots --freq f150 --oname polang_err_f150.pdf
  python plot_polangle_error.py -o plots --freq f220 --oname polang_err_f220.pdf
  #+END_SRC
  fix colormap
  #+BEGIN_SRC bash
    python plot_polangle_error.py -o plots --freq f090 --oname polang_err_f090.pdf \
           --downgrade 4 --max 20 --cmap gray
    python plot_polangle_error.py -o plots --freq f150 --oname polang_err_f150.pdf \
           --downgrade 4 --max 20 --cmap gray
    python plot_polangle_error.py -o plots --freq f220 --oname polang_err_f220.pdf \
           --downgrade 4 --max 20 --cmap gray
  #+END_SRC
** plot magnetic field orientation
- script plot_mag.py
#+BEGIN_SRC 
python plot_mag.py -o plots --freq f090 --oname mag_f090.pdf
python plot_mag.py -o plots --freq f150 --oname mag_f150.pdf
python plot_mag.py -o plots --freq f220 --oname mag_f220.pdf
#+END_SRC
** plot one coadd map only
This is to facilitate object identification work
#+BEGIN_SRC bash
python plot_map_1band.py --freq f090 --oname coadd_f090.pdf
python plot_map_1band.py --freq f150 --oname coadd_f150.pdf
python plot_map_1band.py --freq f220 --oname coadd_f220.pdf --max 6
#+END_SRC
** plot mouse object
Mouse is a pulsar travelling at ~300km/s in interstellar medium
creating a cometary feature. This script plots it in different frequency
with the option to substract a dust template using f220.
#+BEGIN_SRC bash
python plot_mouse.py
#+END_SRC
** plot multi-frequency
This uses f090 as red, f150 as green, f220 as blue.
#+BEGIN_SRC bash
python plot_multifreq.py --oname multifreq.pdf -Q 0 -s 1.5
#+END_SRC
color balance
#+BEGIN_SRC bash
python plot_multifreq.py --oname multifreq_balance.pdf --min 2e8 --max 2e9 --norm 3 -Q 10 -s 2 --area half
#+END_SRC
paper plot
#+BEGIN_SRC bash
python plot_multifreq.py --oname multifreq.pdf --min 2e8 --max 2e9 --norm 1 -Q 3 -s 3 --area full
#+END_SRC
** plot magnetic field of some region of interests
The mouse object with temperature as underlay
#+BEGIN_SRC bash
  python plot_mag.py -o plots --freq f090 --oname mag_mouse_f090.pdf \
         --underlay T --min 2500 --max 7000 --downgrade 2 --box [[-0.9,-0.65],[-0.7,-0.8]]
#+END_SRC
Around Sag A*
#+BEGIN_SRC bash
  python plot_mag.py -o plots --freq f090 --oname mag_SagA_f090_P.pdf \
         --underlay P --min 0 --max 3e3 --box [[-0.17,0.08],[0.10,-0.20]] --downgrade 1
  python plot_mag.py -o plots --freq f150 --oname mag_SagA_f150_P.pdf \
         --underlay P --min 0 --max 2e3 --box [[-0.17,0.08],[0.10,-0.20]] --downgrade 1
#+END_SRC
** plot multi panel view of tornado object
Around the tornado object: 357.65 -0.08
#+BEGIN_SRC bash
  python plot_region.py -o plots --oname map_tornado.pdf \
         --box "[[-0.25, -2.15],[0.05, -2.45]]" --dust-removal \
         --tmax 7000,5000 --pmax 500,300
#+END_SRC
** plot radio arc magnetic field orientation
TBD
** plot spectral indices
ratio of f090 and f150, and the resulting spectral index is compared to
a fiducial index of synchrotron radiation beta = -3.1
#+BEGIN_SRC bash
python plot_spectral_indices.py
#+END_SRC
this plots the spectral index instead of its different with synchtrotron
#+BEGIN_SRC bash
python plot_spectral_indices2.py --area dust1 --cmap magma --freq f150
#+END_SRC
** plot signal to noise
#+BEGIN_SRC bash
python plot_snr.py --area full --min 3 --max 50 --save out
python plot_snr.py --area full --min 0 --max 3 --pol --save out
#+END_SRC
** plot planck ivar map for debug
comp 0,1,2 -> T,Q,U
#+BEGIN_SRC bash
python plot_ivar.py --comp 0
python plot_ivar.py --comp 1
python plot_ivar.py --comp 2
#+END_SRC
It shows that planck's noise model sill has the werid patterns seen in
2018 releases
** plot snr masks
#+BEGIN_SRC bash
enplot out/mask_{I,P}_{f090,f150,f220}_snr3.fits --odir plots
#+END_SRC
